export {default as Home} from './Home';
export {default as Login } from './Login';
export {default as Register} from './Register';
export {default as Posts} from './Posts';
export {default as Navbar} from './Navbar';
export { default as Profile } from './Profile';
export { default as CreatePost } from './CreatePost';
export { default as EditPost } from './EditPost';
export { default as Search} from './Search';
export { default as SinglePost } from './SinglePost';